# Generated by Django 5.2.1 on 2025-07-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_hashtag_alter_post_options_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
