# Generated by Django 5.2.1 on 2025-07-09 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Username faqat harflar, raqamlar, nuqta (.) va pastki chiziq (_) dan iborat bo'lishi kerak. Username '.' yoki '_' bilan boshlanmasligi yoki tugamasligi va ketma-ket ikki '.' yoki '__' bo'lmasligi kerak.", regex='^(?!.*[._]{2})(?![._])[a-zA-Z0-9._]{1,30}(?<![._])$'), django.core.validators.MinLengthValidator(3, message="Username kamida 3 ta belgidan iborat bo'lishi kerak.")]),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
