# Generated by Django 5.2.1 on 2025-06-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
